In [1]:
import numpy as np


In [7]:
a = np.array([1,2,3,4,5,6,6,7])

In [15]:
np.zeros((4,5), dtype = str)

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [16]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [22]:
arr = np.tile([1, 2, 3], (6, 1))
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [23]:
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.eye(3))

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
arr.astype(int)
arr.astype(float)
arr.astype(np.int8)


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int8)

In [25]:
arr.dtype


dtype('int64')

In [29]:
arr.shape
arr.ndim
arr.size



18

In [33]:
arr.reshape(3, 6)



array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [ ]:
arr.flatten()
arr.ravel()

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [41]:
arr[1:4]


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [45]:
arr[arr > 2]


array([3, 3, 3, 3, 3, 3])

In [46]:
(arr > 3) & (arr < 8)
(arr == 0) | (arr == 1)


array([[ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False]])

In [47]:
np.sum(arr)
np.mean(arr)
np.median(arr)
np.min(arr)
np.max(arr)
np.std(arr)
np.var(arr)


np.float64(0.6666666666666666)

In [48]:
np.mean(arr, axis=0)  # по колонкам
np.mean(arr, axis=1)  # по строкам


array([2., 2., 2., 2., 2., 2.])

In [49]:
np.where(arr > 5, 1, 0)
# VERY IMPORTANT

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
np.nan
np.isnan(arr)
np.nanmean(arr)
np.nanmedian(arr)


np.float64(2.0)

In [51]:
np.random.rand(5)
np.random.randn(5)
np.random.randint(0, 10, size=5)
np.random.seed(42)


In [52]:
np.sqrt(arr)
np.log(arr)
np.exp(arr)
np.abs(arr)
np.round(arr, 2)


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [53]:
np.dot(a, b)
a @ b
np.linalg.norm(a)
np.linalg.inv(A)


NameError: name 'b' is not defined

In [54]:
np.sort(arr)
np.argsort(arr)
np.unique(arr)
np.unique(arr, return_counts=True)


(array([1, 2, 3]), array([6, 6, 6]))

In [55]:
np.concatenate([a, b])
np.vstack([a, b])
np.hstack([a, b])


NameError: name 'b' is not defined

In [56]:
arr.copy()


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])